### ISSUE TITLE
sidecar error in master

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1392]
https://osparc01.speag.com/graylog/messages/graylog_8/56d64b10-6823-11ea-81d6-0242ac140004

to be checked once the sidecar refactoring is done

```
message
ERROR: [2020-03-17 07:45:57,612/ForkPoolWorker-1] [trace.py:256] Task comp.task[66aeef9c-ee2b-4f85-bd58-27f4b6de3f64] raised unexpected: FileNotFoundError(2, "No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/scu']")
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sidecar/tasks.py", line 9, in pipeline
    from .core import SIDECAR
  File "/usr/local/lib/python3.6/site-packages/sidecar/core.py", line 17, in <module>
    from simcore_sdk import node_ports, node_data
  File "/usr/local/lib/python3.6/site-packages/simcore_sdk/node_ports/__init__.py", line 5, in <module>
    from ._item import Item as Port
  File "/usr/local/lib/python3.6/site-packages/simcore_sdk/node_ports/_item.py", line 5, in <module>
    from . import config, data_items_utils, exceptions, filemanager
  File "/usr/local/lib/python3.6/site-packages/simcore_sdk/node_ports/data_items_utils.py", line 31, in <module>
    _INTERNAL_DIR = Path(tempfile.gettempdir(), "simcorefiles")
  File "/usr/local/lib/python3.6/tempfile.py", line 298, in gettempdir
    tempdir = _get_default_tempdir()
  File "/usr/local/lib/python3.6/tempfile.py", line 233, in _get_default_tempdir
    dirlist)
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '/usr/tmp', '/home/scu']
```

**Comment by sanderegg** [comment]
happens when the nodes hard-drive are full
