### ISSUE TITLE
sidecar logs error related to connection with rabbit

### ISSUE THREAD

**Issue by sanderegg** [ITISFoundation/osparc-simcore#1483]
```
LogType
ERROR
command
/bin/sh services/sidecar/docker/boot.sh
container_id
cc25b88d9932493790867a499c05415520bfcc7575e856d5ea5c60acf60ce292
container_name
master-simcore_master_sidecar.7.rev8blrtkpw92z8paehxtlfpc
created
2020-05-04T07:41:24.777279931Z
image_id
sha256:3bd4bb17acefa13b181bcdf6a7d5dd9b6df035468ca3381f1fb88c0e3daf1629
image_name
itisfoundation/sidecar:master-latest@sha256:fe262ca165a414008e1ea7a4b8ba82a533e4929a00bff054968fd295db2094be
level
3
message
ERROR: [2020-05-04 09:20:32,414/ForkPoolWorker-1] [base_events.py:1296] Task exception was never retrieved
future: <Task finished coro=<RobustConnection.reconnect() done, defined at /home/scu/.venv/lib/python3.6/site-packages/aio_pika/robust_connection.py:149> exception=RuntimeError('<RobustConnection: "amqp://admin:******@master_rabbit:5672/?name=simcore_service_sidecar.rabbitmq_140256819237616" 1 channels> connection closed',)>
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.6/site-packages/aio_pika/robust_connection.py", line 150, in reconnect
    await self.connect()
  File "/home/scu/.venv/lib/python3.6/site-packages/aio_pika/robust_connection.py", line 105, in connect
    raise RuntimeError("{!r} connection closed".format(self))
RuntimeError: <RobustConnection: "amqp://admin:******@master_rabbit:5672/?name=simcore_service_sidecar.rabbitmq_140256819237616" 1 channels> connection closed
source
9fe5c5e201fe
timestamp
2020-05-04T09:20:32.414Z
```

**Comment by sanderegg** [comment]
fixed callbacks bad syntax.
when the connection is cancelled with a CancelledError there is no more an error message as this is normal behaviour from aio_pika.

**Comment by sanderegg** [comment]
using connect method instead of connect_robust seems to fix the issue.
