### ISSUE TITLE
Cannot edit study's info

### ISSUE THREAD

**Issue by ignapas** [ITISFoundation/osparc-simcore#1614]
![badrequest.gif](https://images.zenhubusercontent.com/5caefb2eecad11531cc41380/659ca522-2d03-45f9-91c2-024bcb487ef2)
```
ERROR:servicelib.jsonschema_validation:Node validation error:
Traceback (most recent call last):
  File "/devel/packages/service-library/src/servicelib/jsonschema_validation.py", line 11, in validate_instance
    validate(instance, schema)
  File "/home/scu/.venv/lib/python3.6/site-packages/jsonschema/validators.py", line 934, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('locked', 'resourceType' were unexpected)

Failed validating 'additionalProperties' in schema:
    {'$id': 'https://simcore.io/api/specs/webserver/v0/components/schemas/project-v0.0.1.json',
```

**Comment by ignapas** [comment]
Invalid properties ``locked`` and ``resourceType`` are added to the study object. ``locked`` looks that is added inside ``Store.js/getStudyWState``. I really wanted to avoid filling this class with entity specific code... please, let me know @odeimaiz when you are available to tackle this one

**Comment by ignapas** [comment]
Workaround the problem by deleting the properties before sending the object
