### ISSUE TITLE
adding a user by it's email to a group that does not exist causes a 500 error

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#1762]
```
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    | ERROR:simcore_service_webserver.diagnostics_monitoring:Unexpected server error "<class 'aiohttp.web_exceptions.HTTPInternalServerError'>" from access: 10.0.13.10 "POST /v0/groups/20/users" done in 0.02 secs. Responding with status 500
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    | Traceback (most recent call last):
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/packages/service-library/src/servicelib/rest_middlewares.py", line 71, in _middleware_handler
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     response = await handler(request)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/packages/service-library/src/servicelib/rest_middlewares.py", line 173, in _middleware_handler
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     resp = await handler(request)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/login/decorators.py", line 21, in wrapped
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     ret = await handler(*args, **kwargs)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/security_decorators.py", line 23, in wrapped
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     ret = await handler(request)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/groups_handlers.py", line 123, in add_group_user
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     new_user_email=new_user_email,
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/groups_api.py", line 229, in add_user_in_group
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     user: RowProxy = await _get_user_from_email(app, new_user_email)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/groups_api.py", line 85, in _get_user_from_email
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     raise UserNotFoundError(email=email)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    | simcore_service_webserver.users_exceptions.UserNotFoundError: User with email asd@asd.com not found
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    | During handling of the above exception, another exception occurred:
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    | Traceback (most recent call last):
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/diagnostics_monitoring.py", line 45, in _middleware_handler
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     resp = await handler(request)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiozipkin/aiohttp_helpers.py", line 167, in aiozipkin_middleware
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     resp = await handler(request)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 172, in factory
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     raise response
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 154, in factory
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     response = await handler(request)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/packages/service-library/src/servicelib/rest_middlewares.py", line 108, in _middleware_handler
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     _process_and_raise_unexpected_error(request, err)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/packages/service-library/src/servicelib/rest_middlewares.py", line 59, in _process_and_raise_unexpected_error
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     raise resp
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    | aiohttp.web_exceptions.HTTPInternalServerError: Unexpected Server error
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    | Stack (most recent call last):
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     "__main__", mod_spec)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     exec(code, run_globals)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/ptvsd/__main__.py", line 446, in <module>
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     main(sys.argv)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/ptvsd/__main__.py", line 432, in main
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     run()
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/ptvsd/__main__.py", line 342, in run_module
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     run_module_as_main(target, alter_argv=True)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     "__main__", mod_spec)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     exec(code, run_globals)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/__main__.py", line 15, in <module>
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     sys.exit(main())
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/cli.py", line 124, in main
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     run_service(config)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/application.py", line 85, in run_service
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     web.run_app(app, host=config["main"]["host"], port=config["main"]["port"])
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/web.py", line 433, in run_app
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     reuse_port=reuse_port))
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 475, in run_until_complete
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     self.run_forever()
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 442, in run_forever
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     self._run_once()
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1462, in _run_once
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     handle._run()
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/packages/service-library/src/servicelib/monitor_slow_callbacks.py", line 23, in instrumented
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     retval = _run(self)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiodebug/log_slow_callbacks.py", line 18, in instrumented
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     retval = _run(self)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     self._callback(*self._args)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     resp = await handler(request)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 119, in impl
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     return await handler(request)
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/diagnostics_monitoring.py", line 107, in _middleware_handler
master-simcore_webserver.1.a0fsil9bph59@neagu-wkst    |     stack_info=True,
```

**Comment by GitHK** [comment]
@odeimaiz @sanderegg this might interest you both

**Comment by sanderegg** [comment]
obsolete
