### ISSUE TITLE
bug: webserver restarted and directly failed with this exception

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#1769]
```
e_manager.redis:Starting call to 'None', this is the 3rd time calling it.


WARNING:aiodebug.log_slow_callbacks:Executing <Handle <TaskWakeupMethWrapper object at 0x7f3ff756a348>(<Future finished result=True>)> took 1.043 seconds


Traceback (most recent call last):


  File "/home/scu/.venv/lib/python3.6/site-packages/simcore_service_webserver/resource_manager/redis.py", line 36, in redis_client


    client = await aioredis.create_redis_pool(url, encoding="utf-8")


  File "/home/scu/.venv/lib/python3.6/site-packages/aioredis/commands/__init__.py", line 198, in create_redis_pool


    loop=loop)


  File "/home/scu/.venv/lib/python3.6/site-packages/aioredis/pool.py", line 58, in create_pool


    await pool._fill_free(override_min=False)


  File "/home/scu/.venv/lib/python3.6/site-packages/aioredis/pool.py", line 383, in _fill_free


    conn = await self._create_new_connection(self._address)


  File "/home/scu/.venv/lib/python3.6/site-packages/aioredis/connection.py", line 113, in create_connection


    timeout)


  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 339, in wait_for


    return (yield from fut)


  File "/home/scu/.venv/lib/python3.6/site-packages/aioredis/stream.py", line 24, in open_connection


    lambda: protocol, host, port, **kwds)


  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 754, in create_connection


    infos = f1.result()


  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run


    result = self.fn(*self.args, **self.kwargs)


  File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo


    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):


socket.gaierror: [Errno -2] Name or service not known




The above exception was the direct cause of the following exception:




Traceback (most recent call last):


  File "/home/scu/.venv/bin/simcore-service-webserver", line 8, in <module>


    sys.exit(main())


  File "/home/scu/.venv/lib/python3.6/site-packages/simcore_service_webserver/cli.py", line 124, in main


    run_service(config)


  File "/home/scu/.venv/lib/python3.6/site-packages/simcore_service_webserver/application.py", line 85, in run_service


    web.run_app(app, host=config["main"]["host"], port=config["main"]["port"])


  File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/web.py", line 433, in run_app


    reuse_port=reuse_port))


  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete


    return future.result()


  File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/web.py", line 305, in _run_app


    await runner.setup()


  File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/web_runner.py", line 232, in setup


    self._server = await self._make_server()


  File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/web_runner.py", line 331, in _make_server


    await self._app.startup()


  File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/web_app.py", line 389, in startup


    await self.on_startup.send(self)


  File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/signals.py", line 34, in send


    await receiver(*args, **kwargs)  # type: ignore


  File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/web_app.py", line 495, in _on_startup


    await it.__anext__()


  File "/home/scu/.venv/lib/python3.6/site-packages/simcore_service_webserver/resource_manager/redis.py", line 34, in redis_client


    for attempt in Retrying(**retry_upon_init_policy):


  File "/home/scu/.venv/lib/python3.6/site-packages/tenacity/__init__.py", line 390, in __iter__


    do = self.iter(retry_state=retry_state)


  File "/home/scu/.venv/lib/python3.6/site-packages/tenacity/__init__.py", line 369, in iter


    six.raise_from(retry_exc, fut.exception())


  File "<string>", line 3, in raise_from


tenacity.RetryError: RetryError[<Future at 0x7f3feee01b00 state=finished raised gaierror>]


ERROR:asyncio:Unclosed client session


client_session: <aiohttp.client.ClientSession object at 0x7f3ff0d63ac8>


ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f3ff0d63c1
```

**Comment by pcrespov** [comment]
cannot reproduce
