### ISSUE TITLE
stuck on loading studies

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#2036]
**EDITED**

I managed to reproduce the error where when logging into the service we stuck on the loading studies page.
This has manifested a lot in the e2e recently.

I had my local deployment inactive for more then 12 hours. After logging in I get this page.

![Screenshot 2020-12-09 at 11 03 10](https://user-images.githubusercontent.com/5694077/101615345-4ebe9c80-3a0e-11eb-8ce5-7d47e2cfdadb.png)

I will attach the logs from the webserver. I think it has something to do with this message
```
Diagnostics starts sensing after waiting 63823.48 secs [> 60.00 secs] since submodule init
```
[webserver_error.log](https://github.com/ITISFoundation/osparc-simcore/files/5665077/webserver_error.log)

@sanderegg @pcrespov any ideas?

---
# Added after edit

It might appear the log to be unrelated. There are no errors inside the log which point to the error. I gave it another try and I found out the the `status` and `dags` calls hang for a long time then after a 5 minutes they time out with a 500 error.

[new_webserver_full_2.log](https://github.com/ITISFoundation/osparc-simcore/files/5665199/new_webserver_full_2.log)

See above webserver log and the 2 screenshots. below.

![Screenshot 2020-12-09 at 11 16 22](https://user-images.githubusercontent.com/5694077/101617444-ea510c80-3a10-11eb-9ca9-77e6eed96465.png)

![Screenshot 2020-12-09 at 11 16 38](https://user-images.githubusercontent.com/5694077/101617454-ecb36680-3a10-11eb-9967-233b643d7b0c.png)

**Comment by GitHK** [comment]
After more investigation I found out that the service gets stuck [on this line](https://github.com/ITISFoundation/osparc-simcore/blob/master/services/web/server/src/simcore_service_webserver/catalog.py#L61).

It apparently uses a global requests object which is shared between all other http clients inside the webserver.

I have the above to be present in conjunction with the below error:

```
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    | ERROR: simcore_service_webserver.diagnostics_monitoring:_middleware_handler(110) - Unexpected server error "<class 'aiohttp.web_exceptions.HTTPServiceUnavailable'>" from access: 10.0.19.24 "GET /v0/catalog/dags" done in 42.94 secs. Responding with status 503
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    | Traceback (most recent call last):
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/catalog.py", line 61, in _request_catalog
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     async with session.request(method, url, headers=headers, data=data) as resp:
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     self._resp = await self._coro
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/client.py", line 504, in _request
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     await resp.start(conn)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 847, in start
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     message, payload = await self._protocol.read()  # type: ignore  # noqa
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/streams.py", line 591, in read
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     await self._waiter
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    | concurrent.futures._base.CancelledError
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    | The above exception was the direct cause of the following exception:
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    | Traceback (most recent call last):
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/diagnostics_monitoring.py", line 48, in _middleware_handler
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     resp = await handler(request)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiozipkin/aiohttp_helpers.py", line 167, in aiozipkin_middleware
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     resp = await handler(request)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 172, in factory
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     raise response
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 154, in factory
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     response = await handler(request)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/packages/service-library/src/servicelib/rest_middlewares.py", line 71, in _middleware_handler
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     response = await handler(request)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/packages/service-library/src/servicelib/rest_middlewares.py", line 173, in _middleware_handler
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     resp = await handler(request)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/products.py", line 98, in discover_product_middleware
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     response = await handler(request)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/login/decorators.py", line 21, in wrapped
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     ret = await handler(*args, **kwargs)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/security_decorators.py", line 23, in wrapped
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     ret = await handler(request)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/catalog.py", line 122, in _reverse_proxy_handler
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     request.app, request.method, backend_url, fwd_headers, raw
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/catalog.py", line 81, in _request_catalog
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     raise web.HTTPServiceUnavailable(reason="unavailable catalog service") from err
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    | aiohttp.web_exceptions.HTTPServiceUnavailable: unavailable catalog service
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    | Stack (most recent call last):
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     "__main__", mod_spec)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     exec(code, run_globals)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/ptvsd/__main__.py", line 446, in <module>
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     main(sys.argv)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/ptvsd/__main__.py", line 432, in main
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     run()
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/ptvsd/__main__.py", line 342, in run_module
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     run_module_as_main(target, alter_argv=True)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     "__main__", mod_spec)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     exec(code, run_globals)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/__main__.py", line 15, in <module>
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     sys.exit(main())
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/cli.py", line 108, in main
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     run_service(config)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/application.py", line 95, in run_service
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     web.run_app(app, host=config["main"]["host"], port=config["main"]["port"])
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/home/scu/.venv/lib/python3.6/site-packages/aiohttp/web.py", line 433, in run_app
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     reuse_port=reuse_port))
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 475, in run_until_complete
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     self.run_forever()
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 442, in run_forever
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     self._run_once()
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1462, in _run_once
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     handle._run()
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/packages/service-library/src/servicelib/monitor_slow_callbacks.py", line 23, in instrumented
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     retval = _run(self)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     self._callback(*self._args)
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |   File "/devel/services/web/server/src/simcore_service_webserver/diagnostics_monitoring.py", line 110, in _middleware_handler
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    |     stack_info=True,
master-simcore_webserver.1.ya1zf981ljkn@neagu-wkst    | DEBUG: simcore_service_webserver.diagnostics_core:is_sensing_enabled(69) - Diagnostics starts sensing after waiting 63823.48 secs [> 60.00 secs] since submodule init
```

The above error is caused by the monitoring which when the application starts works as expected. When this breaks, the catalog at some point, also stops working.

I had issues trying to reproduce the error, also tried to lower the amount of parallel connections inside the `ClientSession` but had no success. Only obtained it once after leaving the entire application idle form more then  half a day.

**Comment by pcrespov** [comment]
I think you should look into the catalog service logs not in the webserver. My guess, with the information you show above, is that the webserver is waiting for the catalog to respond and it takes so long that it times out.  
We have experienced in the past operations hanging in the catalog e.g. because the database cannot allocate more connections.

I will look into it a bit later.

**Comment by GitHK** [comment]
Thanks for the help I will also give this a try.

**Comment by GitHK** [comment]
**I have deleted a comment from @pcrespov by accident**

@pcrespov Was suggesting to have a look at the catalog logs as in the past it has caused issues. He also stated that he will have a look at it.

**Comment by GitHK** [comment]
I've checked what suggested above and the issue is that after 5 minutes the requests timeout and not HTTP calls hit the **catalog service**.

**Comment by GitHK** [comment]
@pcrespov I found a way to reproduce it in a local environment:

- start the simcore locally
- wait for everything to be up and ready and make sure you can login and visualise your studies
- go to `services/catalog/src/simcore_service_catalog/db/repositories/services.py` -> add a new line -> wait for the service to restart -> Remove the added line -> wait for the service to restart. **Note** if you change the `services/catalog/src/simcore_service_catalog/core/background_tasks.py` file the issue will not appear.
- close the tab and reopen it again. you will see the hanging requests to `/dags` and `/services` in the js debugger.

**Comment by odeimaiz** [comment]
@GitHK can this one be closed?

**Comment by GitHK** [comment]
Closing because it was no longer detected. In case this occurs again will reopen it.
