### ISSUE TITLE
 remove_project_interactive_services raises ``aioredlock.errors.LockError: Can not release the lock

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#2783]
```cmd
pytest \ tests/unit/with_dbs/02/test_access_to_studies.py::test_access_cookie_of_expired_user
```

```cmd
tests/unit/with_dbs/02/test_access_to_studies.py::test_access_cookie_of_expired_user[pyloop]
  /home/crespo/devp/osparc-simcore/.venv/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object remove_project_interactive_services at 0x7f70bbfdfbc0>
  
  Traceback (most recent call last):
    File "/home/crespo/devp/osparc-simcore/services/web/server/src/simcore_service_webserver/projects/projects_api.py", line 260, in lock_with_notification
      yield
    File "/home/crespo/devp/osparc-simcore/services/web/server/src/simcore_service_webserver/projects/projects_api.py", line 307, in remove_project_interactive_services
      await director_v2_api.stop_services(
  GeneratorExit
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/crespo/devp/osparc-simcore/services/web/server/src/simcore_service_webserver/projects/projects_api.py", line 260, in lock_with_notification
      yield
    File "/home/crespo/devp/osparc-simcore/.venv/lib/python3.8/site-packages/aioredlock/lock.py", line 17, in __aexit__
      await self.lock_manager.unlock(self)
    File "/home/crespo/devp/osparc-simcore/.venv/lib/python3.8/site-packages/aioredlock/algorithm.py", line 203, in unlock
      await self.redis.unset_lock(lock.resource, lock.id)
    File "/home/crespo/devp/osparc-simcore/.venv/lib/python3.8/site-packages/aioredlock/redis.py", line 403, in unset_lock
      raise LockError('Can not release the lock')
  aioredlock.errors.LockError: Can not release the lock
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/crespo/devp/osparc-simcore/services/web/server/src/simcore_service_webserver/projects/projects_api.py", line 307, in remove_project_interactive_services
      await director_v2_api.stop_services(
    File "/home/crespo/.pyenv/versions/3.8.10/lib/python3.8/contextlib.py", line 189, in __aexit__
      await self.gen.athrow(typ, value, traceback)
    File "/home/crespo/devp/osparc-simcore/services/web/server/src/simcore_service_webserver/projects/projects_api.py", line 267, in lock_with_notification
      prj_states: ProjectState = await get_project_states_for_user(
    File "/home/crespo/devp/osparc-simcore/services/web/server/src/simcore_service_webserver/projects/projects_api.py", line 820, in get_project_states_for_user
      lock_state, computation_task = await logged_gather(
    File "/home/crespo/devp/osparc-simcore/packages/service-library/src/servicelib/utils.py", line 110, in logged_gather
      results = await asyncio.gather(*wrapped_tasks, return_exceptions=True)
    File "/home/crespo/.pyenv/versions/3.8.10/lib/python3.8/asyncio/tasks.py", line 824, in gather
      fut = ensure_future(arg, loop=loop)
    File "/home/crespo/.pyenv/versions/3.8.10/lib/python3.8/asyncio/tasks.py", line 672, in ensure_future
      task = loop.create_task(coro_or_future)
    File "/home/crespo/.pyenv/versions/3.8.10/lib/python3.8/asyncio/base_events.py", line 429, in create_task
      self._check_closed()
    File "/home/crespo/.pyenv/versions/3.8.10/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
```

**Comment by pcrespov** [comment]
#2898 fixed thisone
