### ISSUE TITLE
Issues with anyio director-v2 causes dynamic-sidecar to fail

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3026]
This issue should no longer be present in anyio/httpx  but apparently it is still there with:

- `httpcore==0.14.4` 
- `httpx==0.21.3`
- `anyio==3.2.1`

Reference:
- https://github.com/encode/httpx/issues/1885

```
2022-05-06T12:42:08.421106720Z ERROR:simcore_service_director_v2.modules.dynamic_sidecar.scheduler.task:Observation of dy-sidecar_f7b1f6ab-0c86-4a73-aee2-85175ffdb6c4 failed:
2022-05-06T12:42:08.421156054Z Traceback (most recent call last):
2022-05-06T12:42:08.421163670Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/task.py", line 361, in observing_single_service
2022-05-06T12:42:08.421169692Z     await _apply_observation_cycle(self.app, self, scheduler_data)
2022-05-06T12:42:08.421186852Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/task.py", line 85, in _apply_observation_cycle
2022-05-06T12:42:08.421192168Z     await update_dynamic_sidecar_health(app, scheduler_data)
2022-05-06T12:42:08.421197134Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/client_api.py", line 429, in update_dynamic_sidecar_health
2022-05-06T12:42:08.421202361Z     is_healthy = await api_client.is_healthy(service_endpoint)
2022-05-06T12:42:08.421207380Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/client_api.py", line 94, in is_healthy
2022-05-06T12:42:08.421212620Z     response = await self._client.get(
2022-05-06T12:42:08.421217649Z   File "/home/scu/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1736, in get
2022-05-06T12:42:08.421222627Z     return await self.request(
2022-05-06T12:42:08.421227415Z   File "/home/scu/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1513, in request
2022-05-06T12:42:08.421232228Z     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
2022-05-06T12:42:08.421237521Z   File "/home/scu/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1600, in send
2022-05-06T12:42:08.421242557Z     response = await self._send_handling_auth(
2022-05-06T12:42:08.421247421Z   File "/home/scu/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
2022-05-06T12:42:08.421252572Z     response = await self._send_handling_redirects(
2022-05-06T12:42:08.421257350Z   File "/home/scu/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
2022-05-06T12:42:08.421262602Z     response = await self._send_single_request(request)
2022-05-06T12:42:08.421267408Z   File "/home/scu/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1702, in _send_single_request
2022-05-06T12:42:08.421272532Z     response = await transport.handle_async_request(request)
2022-05-06T12:42:08.421278596Z   File "/home/scu/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 308, in handle_async_request
2022-05-06T12:42:08.421283755Z     resp = await self._pool.handle_async_request(req)
2022-05-06T12:42:08.421288591Z   File "/home/scu/.venv/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 218, in handle_async_request
2022-05-06T12:42:08.421293651Z     async with self._pool_lock:
2022-05-06T12:42:08.421298481Z   File "/home/scu/.venv/lib/python3.9/site-packages/httpcore/_synchronization.py", line 15, in __aenter__
2022-05-06T12:42:08.421303578Z     await self._lock.acquire()
2022-05-06T12:42:08.421308235Z   File "/home/scu/.venv/lib/python3.9/site-packages/anyio/_core/_synchronization.py", line 119, in acquire
2022-05-06T12:42:08.421313333Z     self.acquire_nowait()
2022-05-06T12:42:08.421318064Z   File "/home/scu/.venv/lib/python3.9/site-packages/anyio/_core/_synchronization.py", line 146, in acquire_nowait
2022-05-06T12:42:08.421328075Z     raise RuntimeError('Attempted to acquire an already held Lock')
```

**Comment by GitHK** [comment]
should have disappeared, since libraries were updated
