### ISSUE TITLE
Incompatible ``job_id`` format raises exception while parsing (``parse_dask_job_id``)

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3054]
In dalco staging found the following error:

```log
ERROR:simcore_service_director_v2.modules.comp_scheduler.base_scheduler:Project 43b58207-6520-43bf-a890-0727643c0c03: task=CompTaskAtDB(project_id=UUID('43b58207-6520-43bf-a890-0727643c0c03'), node_id=UUID('0b569007-f8e6-5904-898a-ac63eb731efa'), job_id='367ea609-7360-4f3e-a8e0-46b61ede6ce2', node_schema=NodeSchema(inputs={'input_1': ServiceInput(display_order=1.0, label='Input data', description='Any code, requirements or data file', property_type='data:*/*', content_schema=None, file_to_key_map=None, unit=None, default_value=None, widget=None)}, outputs={'output_1': _ServiceOutputOverride(display_order=1.0, label='Output data', description='All data produced by the script is zipped as output_data.zip', property_type='data:*/*', content_schema=None, file_to_key_map={'output_data.zip': 'output_1'}, unit=None, widget=None)}), inputs={'input_1': SimCoreFileLink(store='0', path='api/5f45da4b-970b-3606-b4fe-097a985563c2/LFCreation.zip', label='LFCreation.zip', e_tag='ea0620ad624067c63ee13ec4cd8eaffb', dataset=None), 'NCPU': 2.0}, outputs={}, run_hash=None, image=Image(name='simcore/services/comp/s4l-python-runner', tag='1.0.9', requires_gpu=False, requires_mpi=False, node_requirements=NodeRequirements(cpu=1.0, gpu=0, ram=134217728, mpi=0), command=['run']), submit=datetime.datetime(2021, 9, 3, 14, 29, 8, 579659), start=datetime.datetime(2021, 9, 3, 14, 46, 39, 208334), end=datetime.datetime(2021, 9, 3, 14, 46, 37, 120578), state=<RunningState.STARTED: 'STARTED'>, task_id=961547, internal_id=1, node_class=<NodeClass.COMPUTATIONAL: 'COMPUTATIONAL'>, errors=None) has backend_state=<RunningState.UNKNOWN: 'UNKNOWN'>. The task disappeared from the dask-scheduler, aborting the computational pipeline!
ERROR:simcore_service_director_v2.modules.comp_scheduler.background_task:Unexpected error in computational scheduler task, restarting scheduler now...
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/comp_scheduler/background_task.py", line 21, in scheduler_task
    await scheduler.schedule_all_pipelines()
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py", line 118, in schedule_all_pipelines
    await asyncio.gather(
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py", line 312, in _schedule_pipeline
    await self._update_states_from_comp_backend(
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/comp_scheduler/base_scheduler.py", line 264, in _update_states_from_comp_backend
    await self._process_completed_tasks(user_id, cluster_id, tasks_completed)
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py", line 131, in _process_completed_tasks
    await asyncio.gather(
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/comp_scheduler/dask_scheduler.py", line 157, in _process_task_result
    ) = parse_dask_job_id(task.job_id)
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/utils/dask.py", line 92, in parse_dask_job_id
    parts[1],
IndexError: list index out of range
```

This is due to backwards incompatibility of the format in ``job_id`` column in ``comp_task`` table. I found at least three version of this ``job_id`` and created this test setup in case you want to use it

```python
import pytest

@pytest.mark.parametrize(
    "comp_task_row",
    [
        # v1
        {
            "task_id": "919171",
            "project_id": "32130480-fe9a-11eb-92d3-02420a0b00bd",
            "node_id": "b022b49c-8c42-4014-9f47-9c5c3f687fea",
            "job_id": "5f46614f-156a-48dc-b3a1-d18ea081552e",
        },
        # v2
        {
            "task_id": "1460960",
            "project_id": "ac064134-4306-11ec-a206-02420a0b2350",
            "node_id": "e0788777-a386-4f9b-bbc3-a2fb7c3cdfcc",
            "job_id": "simcore/services/comp/osparc-python-runner-tensorflow_1.0.4__projectid_ac064134-4306-11ec-a206-02420a0b2350__nodeid_e0788777-a386-4f9b-bbc3-a2fb7c3cdfcc__098b8416-44f3-4146-8b5c-be4361b896a1",
        },
        # v3
        {
            "task_id": "1801993",
            "project_id": "febe4179-fa0b-410f-a8e4-20e71c6e37c2",
            "node_id": "7a00525c-f213-5271-8e2d-a20f944f8dd6",
            "job_id": "simcore/services/comp/latex-compile:1.3.0:userid_21790:projectid_febe4179-fa0b-410f-a8e4-20e71c6e37c2:nodeid_7a00525c-f213-5271-8e2d-a20f944f8dd6:uuid_c3cdf06c-26e3-4ae0-b20f-21e2abd30017",
        },
    ],
)
def test_backwards_compatibility_parse_dask_job_id(
    comp_task_row: dict[str, str]
):
     _,_,project_id, node_id, _ = parse_dask_job_id(comp_task_row["job_id"])
     assert project_id == comp_task_row["project_id"]
     assert node_id == comp_task_row["node_id"]

```

Some thoughts about possible solutions

- Drop: Can remove these lines from table. The only risk is that the task really did not run and gets completely lost
- Force upgrade: Have a script that upgrades database old format into the latest format
- Lazy upgrade: Have an automatic conversion upon read of a row or keep some sort of backwards compatibility

And regarding this formatting/parsing of ``job_id``. Would it suffice to serialize/deserialize in a json string from a pydantic model. I had the same scenario with automatic tagging and I see little advantage having other sort of string serialization format.

**Comment by sanderegg** [comment]
This has disappeared. thus closing the issue.
