### ISSUE TITLE
UI Rendering error in Preferences

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#364]
Start user references window
Tabs load slowly
Debug console shows errors. See below:

```
Native.js? [sm]:58 011015 qx.ui.core.queue.Appearance: Error in the 'Appearance' queue:Error: Error in property decorator of class qx.ui.form.TextField in method setThemedDecorator with incoming value 'flat': Is invalid! Error: Error in property decorator of class qx.ui.form.TextField in method setThemedDecorator with incoming value 'flat': Is invalid!
http://localhost:9081/transpiled/qx/core/Property.js:548:15,eval at __installFunctionFromCode (http://localhost:9081/transpiled/qx/core/Property.js:595:36,eval at __installFunctionFromCode (http://localhost:9081/transpiled/qx/core/Property.js:595:36,http://localhost:9081/transpiled/qx/ui/core/Widget.js:2383:86,http://localhost:9081/transpiled/qx/ui/core/queue/Appearance.js:82:17,http://localhost:9081/transpiled/qx/ui/core/queue/Manager.js:136:45,http://localhost:9081/transpiled/qx/ui/core/queue/Manager.js:200:9,http://localhost:9081/transpiled/qx/ui/core/queue/Manager.js:108:14,http://localhost:9081/transpiled/qx/event/dispatch/Direct.js:103:39,http://localhost:9081/transpiled/qx/event/Utils.js:96:22,http://localhost:9081/transpiled/qx/event/dispatch/Direct.js:102:28,http://localhost:9081/transpiled/qx/lang/normalize/Array.js:110:22,http://localhost:9081/transpiled/qx/event/dispatch/Direct.js:91:21,http://localhost:9081/transpiled/qx/Interface.js:463:31,http://localhost:9081/transpiled/qx/event/Manager.js:802:52,http://localhost:9081/transpiled/qx/event/Registration.js:311:42
```

**Comment by pcrespov** [comment]
obsolete
