### ISSUE TITLE
Unexpected status error

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3853]
```
2023-02-08T12:29:36.078971813Z ERROR:simcore_service_director_v2.modules.dynamic_sidecar.scheduler._core._observer:Observation of service_name='dy-sidecar_5ff92c84-28e1-471a-9ecd-ee1e7593c267'  unexpectedly failed [OEC:139785442014208]
2023-02-08T12:29:36.078974391Z Traceback (most recent call last):
2023-02-08T12:29:36.078975924Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_observer.py", line 140, in observing_single_service
2023-02-08T12:29:36.078977245Z     await _apply_observation_cycle(scheduler, scheduler_data)
2023-02-08T12:29:36.078977739Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_observer.py", line 69, in _apply_observation_cycle
2023-02-08T12:29:36.078978841Z     await dynamic_scheduler_event.action(app, scheduler_data)
2023-02-08T12:29:36.078979165Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events.py", line 378, in action
2023-02-08T12:29:36.078979516Z     raise UnexpectedContainerStatusError(
2023-02-08T12:29:36.078980512Z simcore_service_director_v2.modules.dynamic_sidecar.errors.UnexpectedContainerStatusError: Unexpected status from containers: [DockerContainerInspect(container_state=ContainerState(Status=<Status2.exited: 'exited'>, Running=False, Paused=False, Restarting=False, OOMKilled=False, Dead=False, Pid=0, ExitCode=1, Error='', StartedAt='2023-02-08T12:29:33.17138949Z', FinishedAt='2023-02-08T12:29:33.232229779Z', Health=Health(Status=<Status.unhealthy: 'unhealthy'>, FailingStreak=0, Log=[])), name='/dy-sidecar-5ff92c84-28e1-471a-9ecd-ee1e7593c267-1-s4l-core', id='2ba9a5283427c78b411e8ee1e3f387cd4fa80256e97dd8acb18f1b82e1f2eb7a', status=<Status2.exited: 'exited'>)]
```

@mguidon we need to followup on this one

**Comment by GitHK** [comment]
stale, closing
