### ISSUE TITLE
Autoscaling update ot of sequence error in docker

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#3860]
```
ERROR:servicelib.background_task:Unhandled exception: DockerError(500, 'rpc error: code = Unknown desc = update out of sequence')
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/logging_utils.py", line 202, in log_catch

d
  File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/background_task.py", line 33, in _periodic_scheduled_task
    await task(**task_kwargs)
  File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/redis_utils.py", line 30, in wrapper
    return await func(*args, **kwargs)
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_autoscaling/dynamic_scaling_core.py", line 549, in cluster_scaling_from_labelled_services
    cluster = await _scale_cluster(app, cluster)
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_autoscaling/dynamic_scaling_core.py", line 529, in _scale_cluster
    cluster = await _deactivate_empty_nodes(app, cluster)
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_autoscaling/dynamic_scaling_core.py", line 72, in _deactivate_empty_nodes
    await asyncio.gather(
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_autoscaling/utils/utils_docker.py", line 367, in set_node_availability
    return await tag_node(
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_autoscaling/utils/utils_docker.py", line 351, in tag_node
    await docker_client.nodes.update(
  File "/home/scu/.venv/lib/python3.9/site-packages/aiodocker/nodes.py", line 64, in update
    response = await self.docker._query_json(
  File "/home/scu/.venv/lib/python3.9/site-packages/aiodocker/docker.py", line 300, in _query_json
    async with self._query(
  File "/home/scu/.venv/lib/python3.9/site-packages/aiodocker/utils.py", line 309, in __aenter__
    resp = await self._coro
  File "/home/scu/.venv/lib/python3.9/site-packages/aiodocker/docker.py", line 275, in _do_query
    raise DockerError(response.status, json.loads(what.decode("utf8")))
```

**Comment by sanderegg** [comment]
@GitHK 
while that error is not nice to see in the logs, it is not a problem as the autoscaling is resilient to it and will re-run 10 seconds later without issue.
I'll try to fix it if I manage to get some time around it.
