### ISSUE TITLE
docker version parsing

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#3946]
DockerVersion validator is not apparently happy with the current version of docker.

NOTE: when fixing the validator the bash script for removing the volumes will fail since the new dind docker image is not happy at all.

- Requires to be fixed https://github.com/ITISFoundation/osparc-simcore/issues/3446 otherwise the volume removal will not work any longer.
- closes https://github.com/ITISFoundation/osparc-simcore/issues/3952

```
ERROR:simcore_service_director_v2.modules.dynamic_sidecar.scheduler._core._observer:Observation of service_name='dy-sidecar_d3b7dceb-c5d1-5044-b98d-6699e0ed23a3'  unexpectedly failed [OEC:140051059082848]
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_observer.py", line 141, in observing_single_service
    await _apply_observation_cycle(scheduler, scheduler_data)
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_observer.py", line 70, in _apply_observation_cycle
    await dynamic_scheduler_event.action(app, scheduler_data)
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events.py", line 603, in action
    await attempt_pod_removal_and_data_saving(app, scheduler_data)
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events_utils.py", line 322, in attempt_pod_removal_and_data_saving
    await service_remove_sidecar_proxy_docker_networks_and_volumes(
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events_utils.py", line 193, in service_remove_sidecar_proxy_docker_networks_and_volumes
    await remove_volumes_from_node(
  File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/docker_api/_volume.py", line 62, in remove_volumes_from_node
    docker_version: DockerVersion = parse_obj_as(
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[DockerVersion]
__root__
  23.0.0 appears not to be a valid docker version (type=value_error)
WARNING:simcore_service_director_v2.modules.dynamic_sidecar.docker_api._core:Skipped labels update for service 'dy-sidecar_d3b7dceb-c5d1-5044-b98d-6699e0ed23a3' which could not be found.
```

**Comment by GitHK** [comment]
this can now be considered closed
