### ISSUE TITLE
Storage tracebacks

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#4073]
Storage service requires some love.

```
2023-04-06T01:32:03.554912414Z ERROR:servicelib.aiohttp.monitoring:Unexpected server error "<class 'aiohttp.web_exceptions.HTTPGatewayTimeout'>" from access: 10.11.1.23 "GET /v0/locations/0/files/metadata" done in 60.00 secs. Responding with status 504
2023-04-06T01:32:03.554919314Z Traceback (most recent call last):
2023-04-06T01:32:03.554919874Z   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
2023-04-06T01:32:03.554921184Z     return fut.result()
2023-04-06T01:32:03.554922054Z asyncio.exceptions.CancelledError
2023-04-06T01:32:03.554922654Z 
2023-04-06T01:32:03.554923004Z The above exception was the direct cause of the following exception:
2023-04-06T01:32:03.554923274Z 
2023-04-06T01:32:03.554923494Z Traceback (most recent call last):
2023-04-06T01:32:03.554924094Z   File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/aiohttp/rest_middlewares.py", line 76, in _middleware_handler
2023-04-06T01:32:03.554924414Z     response = await handler(request)
2023-04-06T01:32:03.554924854Z   File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/aiohttp/rest_middlewares.py", line 213, in _middleware_handler
2023-04-06T01:32:03.554925034Z     resp: _ResponseOrBodyData = await handler(request)
2023-04-06T01:32:03.554925344Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_storage/utils_handlers.py", line 27, in dsm_exception_handler
2023-04-06T01:32:03.554925674Z     return await handler(request)
2023-04-06T01:32:03.554925874Z   File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/aiohttp/long_running_tasks/_error_handlers.py", line 14, in base_long_running_error_handler
2023-04-06T01:32:03.554926104Z     return await handler(request)
2023-04-06T01:32:03.554926864Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_storage/handlers_files.py", line 63, in get_files_metadata
2023-04-06T01:32:03.554927134Z     data: list[FileMetaData] = await dsm.list_files(
2023-04-06T01:32:03.554927444Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_storage/simcore_s3_dsm.py", line 121, in list_files
2023-04-06T01:32:03.554927784Z     async with self.engine.acquire() as conn, conn.begin():
2023-04-06T01:32:03.554928164Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiopg/utils.py", line 82, in __aenter__
2023-04-06T01:32:03.554928534Z     self._obj = await self._coro
2023-04-06T01:32:03.554928934Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiopg/sa/connection.py", line 237, in _begin
2023-04-06T01:32:03.554929294Z     await self._begin_impl(isolation_level, readonly, deferrable)
2023-04-06T01:32:03.554929924Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiopg/sa/connection.py", line 252, in _begin_impl
2023-04-06T01:32:03.554930154Z     await cursor.execute(stmt)
2023-04-06T01:32:03.554931084Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiopg/connection.py", line 426, in execute
2023-04-06T01:32:03.554931434Z     await self._conn._poll(waiter, timeout)
2023-04-06T01:32:03.554932034Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiopg/connection.py", line 884, in _poll
2023-04-06T01:32:03.554932384Z     raise exc
2023-04-06T01:32:03.554932644Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiopg/connection.py", line 881, in _poll
2023-04-06T01:32:03.554932884Z     await asyncio.wait_for(self._waiter, timeout)
2023-04-06T01:32:03.554934514Z   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
2023-04-06T01:32:03.554934944Z     raise exceptions.TimeoutError() from exc
2023-04-06T01:32:03.554935304Z asyncio.exceptions.TimeoutError
2023-04-06T01:32:03.554935564Z 
2023-04-06T01:32:03.554935794Z The above exception was the direct cause of the following exception:
2023-04-06T01:32:03.554936074Z 
2023-04-06T01:32:03.554936274Z Traceback (most recent call last):
2023-04-06T01:32:03.554936534Z   File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/aiohttp/monitoring.py", line 182, in middleware_handler
2023-04-06T01:32:03.554936794Z     resp = await handler(request)
2023-04-06T01:32:03.554937014Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiozipkin/aiohttp_helpers.py", line 157, in aiozipkin_middleware
2023-04-06T01:32:03.554937204Z     resp = await handler(request)
2023-04-06T01:32:03.554937704Z   File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/aiohttp/rest_middlewares.py", line 133, in _middleware_handler
2023-04-06T01:32:03.554937934Z     raise error_response from err
2023-04-06T01:32:03.554938764Z aiohttp.web_exceptions.HTTPGatewayTimeout
2023-04-06T01:32:03.554939164Z Stack (most recent call last):
2023-04-06T01:32:03.554939534Z   File "/home/scu/.venv/bin/simcore-service-storage", line 8, in <module>
2023-04-06T01:32:03.554939904Z     sys.exit(main())
2023-04-06T01:32:03.554940154Z   File "/home/scu/.venv/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
2023-04-06T01:32:03.554940444Z     return get_command(self)(*args, **kwargs)
2023-04-06T01:32:03.554940684Z   File "/home/scu/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
2023-04-06T01:32:03.554940944Z     return self.main(*args, **kwargs)
2023-04-06T01:32:03.554941814Z   File "/home/scu/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
2023-04-06T01:32:03.554942404Z     rv = self.invoke(ctx)
2023-04-06T01:32:03.554942714Z   File "/home/scu/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
2023-04-06T01:32:03.554943054Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2023-04-06T01:32:03.554943414Z   File "/home/scu/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
2023-04-06T01:32:03.554943664Z     return ctx.invoke(self.callback, **ctx.params)
2023-04-06T01:32:03.554943914Z   File "/home/scu/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
2023-04-06T01:32:03.554944244Z     return __callback(*args, **kwargs)
2023-04-06T01:32:03.554944914Z   File "/home/scu/.venv/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
2023-04-06T01:32:03.554945814Z     return callback(**use_params)  # type: ignore
2023-04-06T01:32:03.554946384Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_storage/cli.py", line 38, in run
2023-04-06T01:32:03.554948504Z     application.run(settings_obj)
2023-04-06T01:32:03.554948874Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_storage/application.py", line 81, in run
2023-04-06T01:32:03.554949284Z     web.run_app(app, host=settings.STORAGE_HOST, port=settings.STORAGE_PORT)
2023-04-06T01:32:03.554949594Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiohttp/web.py", line 516, in run_app
2023-04-06T01:32:03.554949894Z     loop.run_until_complete(main_task)
2023-04-06T01:32:03.554950194Z   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
2023-04-06T01:32:03.554950934Z     self.run_forever()
2023-04-06T01:32:03.554951174Z   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
2023-04-06T01:32:03.554951484Z     self._run_once()
2023-04-06T01:32:03.554951714Z   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
2023-04-06T01:32:03.554951974Z     handle._run()
2023-04-06T01:32:03.554952194Z   File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
2023-04-06T01:32:03.554952464Z     self._context.run(self._callback, *self._args)
2023-04-06T01:32:03.554952704Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
2023-04-06T01:32:03.554954124Z     resp = await request_handler(request)
2023-04-06T01:32:03.554954564Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
2023-04-06T01:32:03.554954974Z     resp = await handler(request)
2023-04-06T01:32:03.554955374Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
2023-04-06T01:32:03.554955684Z     return await handler(request)
2023-04-06T01:32:03.554956024Z   File "/home/scu/.venv/lib/python3.9/site-packages/servicelib/aiohttp/monitoring.py", line 226, in middleware_handler
2023-04-06T01:32:03.554956644Z     log.error(
2023-04-06T01:46:29.132131216Z ERROR:simcore_service_storage.dsm_cleaner:Unhandled error in dsm cleaner task, restarting task...
2023-04-06T01:46:29.132133616Z Traceback (most recent call last):
2023-04-06T01:46:29.132134406Z   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 490, in wait_for
2023-04-06T01:46:29.132134966Z     return fut.result()
2023-04-06T01:46:29.132135296Z asyncio.exceptions.CancelledError
2023-04-06T01:46:29.132135606Z 
2023-04-06T01:46:29.132135876Z The above exception was the direct cause of the following exception:
2023-04-06T01:46:29.132136066Z 
2023-04-06T01:46:29.132136466Z Traceback (most recent call last):
2023-04-06T01:46:29.132137016Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_storage/dsm_cleaner.py", line 48, in dsm_cleaner_task
2023-04-06T01:46:29.132137436Z     await simcore_s3_dsm.clean_expired_uploads()
2023-04-06T01:46:29.132138036Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_storage/simcore_s3_dsm.py", line 709, in clean_expired_uploads
2023-04-06T01:46:29.132138916Z     await self._clean_expired_uploads()
2023-04-06T01:46:29.132139446Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_storage/simcore_s3_dsm.py", line 591, in _clean_expired_uploads
2023-04-06T01:46:29.132139786Z     list_of_expired_uploads = await db_file_meta_data.list_fmds(
2023-04-06T01:46:29.132140166Z   File "/home/scu/.venv/lib/python3.9/site-packages/simcore_service_storage/db_file_meta_data.py", line 116, in list_fmds
2023-04-06T01:46:29.132140726Z     return [FileMetaDataAtDB.from_orm(row) async for row in await conn.execute(stmt)]
2023-04-06T01:46:29.132141346Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiopg/sa/connection.py", line 168, in _execute
2023-04-06T01:46:29.132143576Z     await cursor.execute(str(compiled), post_processed_params[0])
2023-04-06T01:46:29.132144406Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiopg/connection.py", line 426, in execute
2023-04-06T01:46:29.132145336Z     await self._conn._poll(waiter, timeout)
2023-04-06T01:46:29.132147116Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiopg/connection.py", line 884, in _poll
2023-04-06T01:46:29.132148616Z     raise exc
2023-04-06T01:46:29.132149296Z   File "/home/scu/.venv/lib/python3.9/site-packages/aiopg/connection.py", line 881, in _poll
2023-04-06T01:46:29.132150846Z     await asyncio.wait_for(self._waiter, timeout)
2023-04-06T01:46:29.132152706Z   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
2023-04-06T01:46:29.132153236Z     raise exceptions.TimeoutError() from exc
2023-04-06T01:46:29.132153776Z asyncio.exceptions.TimeoutError
```

**Comment by sanderegg** [comment]
outdated and not helpful.
