### ISSUE TITLE
Flaky build docker images

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4398]
I wonder if this has something to do with the caching ...

![image](https://github.com/ITISFoundation/osparc-simcore/assets/32402063/85d4b2e8-03c1-41fc-babd-c20c0a1f4674)

https://github.com/ITISFoundation/osparc-simcore/actions/runs/5336266183/jobs/9670707667?pr=4395#step:7:4961

**Comment by pcrespov** [comment]
I noticed that this happens sometimes as well in my computer:

```cmd
#134 16.65 Installing collected packages: pygments, mdurl, markdown-it-py, simcore-models-library, rich, simcore-settings-library, simcore-service-library, simcore-service-agent
#134 18.81 ERROR: Exception:
#134 18.81 Traceback (most recent call last):
#134 18.81   File "/home/scu/.venv/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
#134 18.81     status = run_func(*args)
#134 18.81   File "/home/scu/.venv/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
#134 18.81     return func(self, options, args)
#134 18.81   File "/home/scu/.venv/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 449, in run
#134 18.81     installed = install_given_reqs(
#134 18.81   File "/home/scu/.venv/lib/python3.10/site-packages/pip/_internal/req/__init__.py", line 72, in install_given_reqs
#134 18.81     requirement.install(
#134 18.81   File "/home/scu/.venv/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 800, in install
#134 18.81     install_wheel(
#134 18.81   File "/home/scu/.venv/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 731, in install_wheel
#134 18.81     _install_wheel(
#134 18.81   File "/home/scu/.venv/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 591, in _install_wheel
#134 18.81     file.save()
#134 18.81   File "/home/scu/.venv/lib/python3.10/site-packages/pip/_internal/operations/install/wheel.py", line 390, in save
#134 18.81     shutil.copyfileobj(f, dest)
#134 18.81   File "/usr/local/lib/python3.10/shutil.py", line 195, in copyfileobj
#134 18.81     buf = fsrc_read(length)
#134 18.81   File "/usr/local/lib/python3.10/zipfile.py", line 925, in read
#134 18.81     data = self._read1(n)
#134 18.81   File "/usr/local/lib/python3.10/zipfile.py", line 1015, in _read1
#134 18.81     self._update_crc(data)
#134 18.81   File "/usr/local/lib/python3.10/zipfile.py", line 943, in _update_crc
#134 18.81     raise BadZipFile("Bad CRC-32 for file %r" % self.name)
#134 18.81 zipfile.BadZipFile: Bad CRC-32 for file 'simcore_service_library-1.2.0.dist-info/METADATA'
------
Dockerfile:110
--------------------
 109 |     
 110 | >>> RUN \
 111 | >>>   --mount=type=bind,source=packages,target=/build/packages,rw \
 112 | >>>   --mount=type=bind,source=services/agent,target=/build/services/agent,rw \
 113 | >>>   --mount=type=cache,mode=0755,target=/root/.cache/pip \
 114 | >>>   pip install \
 115 | >>>   --requirement requirements/prod.txt \
 116 | >>>   && pip list -v
 117 |     
--------------------

```

The error seems the same `BadZipFile` and the library as well `simcore_service_ibrary`. I wonder whether we have a funny setup there
