### ISSUE TITLE
metamodeling middleware fails when non-owner runs a project

### ISSUE THREAD

**Issue by pcrespov** [ITISFoundation/osparc-simcore#4493]
### Which deploy/s?
development (master)

### Current Behavior
During a demo while running a computational service, the server returned 500

### Steps To Reproduce
Run a service in a project not owned by you, it will get into

### Anything else?

- A way to avoid temporarily this would be to `WEBSERVER_META_MODELING=0` and `WEBSERVER_VERSION_CONTROL=0`
- These are the logs

```log
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/rest_middlewares.py", line 77, in _middleware_handler
    return await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/rest_middlewares.py", line 167, in _middleware_handler
    resp: _ResponseOrBodyData = await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/products/_middlewares.py", line 70, in discover_product_middleware
    response = await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/meta_modeling/_projects.py", line 78, in projects_redirection_middleware
    response = await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/long_running_tasks/_error_handlers.py", line 14, in base_long_running_error_handler
    return await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/login/decorators.py", line 22, in wrapped
    ret = await handler(*args, **kwargs)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/security/decorators.py", line 23, in wrapped
    ret = await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/security/decorators.py", line 23, in wrapped
    ret = await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/director_v2/_handlers.py", line 185, in get_computation
    project_ids: list[ProjectID] = await run_policy.get_runnable_projects_ids(
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/meta_modeling/_projects.py", line 89, in get_runnable_projects_ids
    return await get_runnable_projects_ids(request, project_uuid)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/meta_modeling/_iterations.py", line 320, in get_runnable_projects_ids
    project: ProjectDict = await vc_repo.get_project(str(project_uuid))
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/meta_modeling/_version_control.py", line 76, in get_project
    project_as_dict = dict(project.items())
AttributeError: 'NoneType' object has no attribute 'items'
```

https://monitoring.osparc-master.speag.com/graylog/messages/graylog_12/d4669bf0-20c3-11ee-9660-0242ac102003

**Comment by pcrespov** [comment]
Discontinued https://github.com/ITISFoundation/osparc-simcore/pull/7182
