### ISSUE TITLE
Pydantic Validation Error on dy-sidecar

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-simcore#4714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

production on-premise (dalco), other (e.g. local)

### Current Behavior

On tip.itis.swiss, machine `public04`, we saw on the logs of the container `dy-sidecar_1fc69fbf-67d9-5b59-b17b-c03170657978`:

```
dy-sidecar_1fc69fbf-67d9-5b59-b17b-c03170657978.1.rb9ijcdig8ao@osparc-public-04    | log_level=ERROR | log_timestamp=2023-09-05 17:27:31,632 | log_source=simcore_service_dynamic_sidecar.core.docker_utils:log_catch(228) | log_uid=None | log_msg=Unhandled exception: 2 validation errors for ParsingModel[_DockerProgressDict]\n__root__ -> progressDetail -> current\n  field required (type=value_error.missing)\n__root__ -> progressDetail -> total\n  field required (type=value_error.missing)\nTraceback (most recent call last):\n  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/logging_utils.py", line 223, in log_catch\n    yield\n  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_dynamic_sidecar/core/docker_utils.py", line 239, in _pull_image_with_progress\n    parse_obj_as(_DockerProgressDict, pull_progress),\n  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as\n  File "pydantic/main.py", line 331, in pydantic.main.BaseModel.__init__\npydantic.error_wrappers.ValidationError: 2 validation errors for ParsingModel[_DockerProgressDict]\n__root__ -> progressDetail -> current\n  field required (type=value_error.missing)\n__root__ -> progressDetail -> total\n  field required (type=value_error.missing)
```

looks like a bug

**Comment by GitHK** [comment]
this was changed a few tines since then. please open a new issue if something similar occurs
