### ISSUE TITLE
No object in S3 for storage Error 

### ISSUE THREAD

**Issue by elisabettai** [ITISFoundation/osparc-simcore#4774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

staging aws (e.g. staging.osparc.io)

### Current Behavior

Opening a study with a jupyter-math (v2.0.9) created before the last changes (storage/rclone, etc...) fails.

### Expected Behavior

I should be able to open an "old" study

### Steps To Reproduce

If you have one, try to open a study in AWS staging that was creates some months ago and that contains a dynamic service

### Anything else?

Error if director-v2:
```
log_level=ERROR | log_timestamp=2023-09-19 08:26:28,106 | log_source=simcore_service_director_v2.modules.dynamic_sidecar.scheduler._core._observer:observing_single_service(151) | log_uid=None | log_msg=Observation of service_name='dy-sidecar_4b9fe82b-eb77-40a1-96c5-0cbc892b2642'  unexpectedly failed [OEC:139818436316320]
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_observer.py", line 140, in observing_single_service
    await _apply_observation_cycle(scheduler, scheduler_data)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_observer.py", line 69, in _apply_observation_cycle
    await dynamic_scheduler_event.action(app, scheduler_data)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events.py", line 403, in action
    await prepare_services_environment(app, scheduler_data)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events_utils.py", line 499, in prepare_services_environment
    await _pull_outputs_and_state()
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/scheduler/_core/_events_utils.py", line 457, in _pull_outputs_and_state
    await logged_gather(*tasks, max_concurrency=2)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/utils.py", line 139, in logged_gather
    raise error
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/utils.py", line 116, in sem_task
    return await task
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/api_client/_public.py", line 386, in pull_service_output_ports
    await self._await_for_result(
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_director_v2/modules/dynamic_sidecar/api_client/_public.py", line 280, in _await_for_result
    async with periodic_task_result(
  File "/usr/local/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/fastapi/long_running_tasks/_context_manager.py", line 112, in periodic_task_result
    result: Optional[Any] = await client.get_task_result(task_id)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/fastapi/long_running_tasks/_client.py", line 100, in request_wrapper
    async for attempt in AsyncRetrying(
  File "/home/scu/.venv/lib/python3.10/site-packages/tenacity/_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "/home/scu/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/fastapi/long_running_tasks/_client.py", line 109, in request_wrapper
    return await request_func(zelf, *args, **kwargs)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/fastapi/long_running_tasks/_client.py", line 180, in get_task_result
    raise TaskClientResultError(message=task_result.error)
servicelib.long_running_tasks._errors.TaskClientResultError: Task simcore_service_dynamic_sidecar.modules.long_running_tasks.task_ports_outputs_pull.cf438d2f-9483-4a36-9451-daca8b43b825 finished with exception: 'No object in S3 storage at 4a02a612-0f38-11ee-bc38-02420a0b01ac/4b9fe82b-eb77-40a1-96c5-0cbc892b2642/outputs/output_1/EFS_results.tar.gz'
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/long_running_tasks/_task.py", line 418, in _progress_task
    return await handler(progress, **task_kwargs)

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_dynamic_sidecar/modules/long_running_tasks.py", line 449, in task_ports_outputs_pull
    transferred_bytes = await nodeports.download_target_ports(

  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/async_utils.py", line 168, in wrapper
    raise wrapped_result

  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/async_utils.py", line 149, in worker
    result = await awaitable

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_dynamic_sidecar/modules/nodeports.py", line 278, in download_target_ports
    results = await logged_gather(

  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/utils.py", line 139, in logged_gather
    raise error

  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/utils.py", line 116, in sem_task
    return await task

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_dynamic_sidecar/modules/nodeports.py", line 199, in _get_data_from_port
    port_data = await port.get(sub_progress)

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_v2/port.py", line 288, in get
    v = await _evaluate()

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_v2/port.py", line 256, in _evaluate
    value = await port_utils.pull_file_from_store(

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_v2/port_utils.py", line 192, in pull_file_from_store
    downloaded_file = await filemanager.download_path_from_s3(

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_common/filemanager.py", line 151, in download_path_from_s3
    download_link = await get_download_link_from_s3(

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_common/filemanager.py", line 71, in get_download_link_from_s3
    file_link = await storage_client.get_download_file_link(

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_common/storage_client.py", line 34, in wrapped
    raise exceptions.S3InvalidPathError(
```

**Comment by GitHK** [comment]
@elisabettai so this one looks pretty strange. At exactly `July 28, 2023, 02:00:00 (UTC+02:00)` the file was deleted. Actually also `4a02a612-0f38-11ee-bc38-02420a0b01ac/4b9fe82b-eb77-40a1-96c5-0cbc892b2642/workspace.zip` was deleted.

**Comment by elisabettai** [comment]
Good catch @GitHK, And it's the same for all my studies in AWS staging...
