### ISSUE TITLE
Permissions issue when saving workspace

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#4837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

production aws (e.g. osparc.io)

### Current Behavior

Apparently some services mess up permissions when saving data inside `worksapce` folder. Such is the case for s4l-lab.

See attached stripped logs.

```
log_level=ERROR | log_timestamp=2023-10-06 13:06:34,525 | log_source=simcore_sdk.node_ports_common.filemanager:upload_path(327) | log_uid=None | log_msg=The upload failed with an unexpected error:
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_common/filemanager.py", line 312, in upload_path
    store_id, e_tag, upload_links = await _upload_to_s3(
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_common/filemanager.py", line 380, in _upload_to_s3
    await r_clone.sync_local_to_s3(
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_common/r_clone.py", line 222, in sync_local_to_s3
    await _sync_sources(
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_common/r_clone.py", line 192, in _sync_sources
    await _async_r_clone_command(
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_common/r_clone.py", line 104, in _async_r_clone_command
    raise RCloneFailedError(
simcore_sdk.node_ports_common.r_clone.RCloneFailedError: Command rclone --config /tmp/tmp5d5hzf2n --retries 3 --transfers 5 --use-mmap --buffer-size 0M --stats-log-level NOTICE --stats 0.5s sync /dy-volumes/home/smu/work/workspace s3-destination:production-simcore/0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace --progress --links --verbose finished with exit code=1:


2023-10-06 13:06:33 ERROR : .config/code-server/Machine: failed to open directory ".config/code-server/Machine": open /dy-volumes/home/smu/work/workspace/.config/code-server/Machine: permission denied
2023-10-06 13:06:33 ERROR : .config/code-server/Machine: failed to open directory ".config/code-server/Machine": open /dy-volumes/home/smu/work/workspace/.config/code-server/Machine: permission denied
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Checks:                28 / 119, 24%
Checks:                28 / 119, 24%
Elapsed time:         0.2s
Elapsed time:         0.2s
Checking:
Checking:

2023-10-06 13:06:33 ERROR : .config/code-server/extensions: failed to open directory ".config/code-server/extensions": open /dy-volumes/home/smu/work/workspace/.config/code-server/extensions: permission denied
2023-10-06 13:06:33 ERROR : .config/code-server/extensions: failed to open directory ".config/code-server/extensions": open /dy-volumes/home/smu/work/workspace/.config/code-server/extensions: permission denied
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (no need to retry)
Errors:                 1 (no need to retry)
Checks:                35 / 121, 29%
Checks:                35 / 121, 29%
Elapsed time:         0.2s
Elapsed time:         0.2s
Checking:
Checking:

2023-10-06 13:06:33 ERROR : .config/code-server/User/globalStorage: failed to open directory ".config/code-server/User/globalStorage": open /dy-volumes/home/smu/work/workspace/.config/code-server/User/globalStorage: permission denied
2023-10-06 13:06:33 ERROR : .config/code-server/User/globalStorage: failed to open directory ".config/code-server/User/globalStorage": open /dy-volumes/home/smu/work/workspace/.config/code-server/User/globalStorage: permission denied
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 2 (no need to retry)
Errors:                 2 (no need to retry)
Checks:                45 / 142, 32%
Checks:                45 / 142, 32%
Elapsed time:         0.2s
Elapsed time:         0.2s
Checking:
Checking:

2023-10-06 13:06:33 ERROR : .config/code-server/User/History: failed to open directory ".config/code-server/User/History": open /dy-volumes/home/smu/work/workspace/.config/code-server/User/History: permission denied
2023-10-06 13:06:33 ERROR : .config/code-server/User/History: failed to open directory ".config/code-server/User/History": open /dy-volumes/home/smu/work/workspace/.config/code-server/User/History: permission denied
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 2 (no need to retry)
Errors:                 2 (no need to retry)
Checks:                46 / 142, 32%
Checks:                46 / 142, 32%
Elapsed time:         0.2s
Elapsed time:         0.2s
Checking:
Checking:

2023-10-06 13:06:34 ERROR : S3 bucket production-simcore path 0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace: not deleting files as there were IO errors
2023-10-06 13:06:34 ERROR : S3 bucket production-simcore path 0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace: not deleting files as there were IO errors
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 4 (no need to retry)
Errors:                 4 (no need to retry)
Checks:               148 / 148, 100%
Checks:               148 / 148, 100%
Elapsed time:         0.3s
Elapsed time:         0.3s
2023-10-06 13:06:34 ERROR : S3 bucket production-simcore path 0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace: not deleting directories as there were IO errors
2023-10-06 13:06:34 ERROR : S3 bucket production-simcore path 0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace: not deleting directories as there were IO errors
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 4 (no need to retry)
Errors:                 4 (no need to retry)
Checks:               148 / 148, 100%
Checks:               148 / 148, 100%
Elapsed time:         0.3s
Elapsed time:         0.3s
2023-10-06 13:06:34 ERROR : Attempt 1/3 failed with 5 errors and: not deleting files as there were IO errors
2023-10-06 13:06:34 ERROR : Attempt 1/3 failed with 5 errors and: not deleting files as there were IO errors
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 5 (retrying may help)
Errors:                 5 (retrying may help)
Checks:               148 / 148, 100%
Checks:               148 / 148, 100%
Elapsed time:         0.3s
Elapsed time:         0.3s
2023-10-06 13:06:34 ERROR : .config/code-server/Machine: failed to open directory ".config/code-server/Machine": open /dy-volumes/home/smu/work/workspace/.config/code-server/Machine: permission denied
2023-10-06 13:06:34 ERROR : .config/code-server/Machine: failed to open directory ".config/code-server/Machine": open /dy-volumes/home/smu/work/workspace/.config/code-server/Machine: permission denied
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Checks:               162 / 202, 80%
Checks:               162 / 202, 80%
Elapsed time:         0.4s
Elapsed time:         0.4s
Checking:
Checking:

2023-10-06 13:06:34 ERROR : .config/code-server/extensions: failed to open directory ".config/code-server/extensions": open /dy-volumes/home/smu/work/workspace/.config/code-server/extensions: permission denied
2023-10-06 13:06:34 ERROR : .config/code-server/extensions: failed to open directory ".config/code-server/extensions": open /dy-volumes/home/smu/work/workspace/.config/code-server/extensions: permission denied
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (no need to retry)
Errors:                 1 (no need to retry)
Checks:               162 / 202, 80%
Checks:               162 / 202, 80%
Elapsed time:         0.4s
Elapsed time:         0.4s
Checking:
Checking:

2023-10-06 13:06:34 ERROR : .config/code-server/User/History: failed to open directory ".config/code-server/User/History": open /dy-volumes/home/smu/work/workspace/.config/code-server/User/History: permission denied
2023-10-06 13:06:34 ERROR : .config/code-server/User/History: failed to open directory ".config/code-server/User/History": open /dy-volumes/home/smu/work/workspace/.config/code-server/User/History: permission denied
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 2 (no need to retry)
Errors:                 2 (no need to retry)
Checks:               186 / 282, 66%
Checks:               186 / 282, 66%
Elapsed time:         0.4s
Elapsed time:         0.4s
Checking:
Checking:

2023-10-06 13:06:34 ERROR : .config/code-server/User/globalStorage: failed to open directory ".config/code-server/User/globalStorage": open /dy-volumes/home/smu/work/workspace/.config/code-server/User/globalStorage: permission denied
2023-10-06 13:06:34 ERROR : .config/code-server/User/globalStorage: failed to open directory ".config/code-server/User/globalStorage": open /dy-volumes/home/smu/work/workspace/.config/code-server/User/globalStorage: permission denied
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 3 (no need to retry)
Errors:                 3 (no need to retry)
Checks:               186 / 284, 65%
Checks:               186 / 284, 65%
Elapsed time:         0.4s
Elapsed time:         0.4s
Checking:
Checking:
Errors:                 4 (no need to retry)
Errors:                 4 (no need to retry)
Checks:               279 / 296, 94%
Checks:               279 / 296, 94%
Elapsed time:         0.5s
Elapsed time:         0.5s
Checking:
Checking:
 *                    TVB7/data/conn/weights.txt: checking
 *                    TVB7/data/conn/weights.txt: checking
 * JR_SG/results/JR with …15/TVBresultsTmstp.npz: checking
 * JR_SG/results/JR with …15/TVBresultsTmstp.npz: checking
 * JR_SG/results/JR with …thon-runner_1.2.0.logs: checking
 * JR_SG/results/JR with …thon-runner_1.2.0.logs: checking
 * JR_SG/results/JR with …75/TVBresultsTmstp.npz: checking
 * JR_SG/results/JR with …75/TVBresultsTmstp.npz: checking
 * JR_SG/results/JR with …thon-runner_1.2.0.logs: checking
 * JR_SG/results/JR with …thon-runner_1.2.0.logs: checking
 * JR_SG/results/JR with ….3/TVBresultsTmstp.npz: checking
 * JR_SG/results/JR with ….3/TVBresultsTmstp.npz: checking
 * JR_SG/results/JR with …thon-runner_1.2.0.logs: checking
 * JR_SG/results/JR with …thon-runner_1.2.0.logs: checking
 * TVB7/results/connectiv…1.aparc/TVBresults.npz: checking
 * TVB7/results/connectiv…1.aparc/TVBresults.npz: checking
2023-10-06 13:06:34 ERROR : S3 bucket production-simcore path 0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace: not deleting files as there were IO errors
2023-10-06 13:06:34 ERROR : S3 bucket production-simcore path 0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace: not deleting files as there were IO errors
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 4 (no need to retry)
Errors:                 4 (no need to retry)
Checks:               296 / 296, 100%
Checks:               296 / 296, 100%
Elapsed time:         0.6s
Elapsed time:         0.6s
2023-10-06 13:06:34 ERROR : S3 bucket production-simcore path 0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace: not deleting directories as there were IO errors
2023-10-06 13:06:34 ERROR : S3 bucket production-simcore path 0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace: not deleting directories as there were IO errors
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 4 (no need to retry)
Errors:                 4 (no need to retry)
Checks:               296 / 296, 100%
Checks:               296 / 296, 100%
Elapsed time:         0.6s
Elapsed time:         0.6s
2023-10-06 13:06:34 ERROR : Attempt 2/3 failed with 5 errors and: not deleting files as there were IO errors
2023-10-06 13:06:34 ERROR : Attempt 2/3 failed with 5 errors and: not deleting files as there were IO errors
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 5 (retrying may help)
Errors:                 5 (retrying may help)
Checks:               296 / 296, 100%
Checks:               296 / 296, 100%
Elapsed time:         0.6s
Elapsed time:         0.6s
2023-10-06 13:06:34 ERROR : .config/code-server/Machine: failed to open directory ".config/code-server/Machine": open /dy-volumes/home/smu/work/workspace/.config/code-server/Machine: permission denied
2023-10-06 13:06:34 ERROR : .config/code-server/Machine: failed to open directory ".config/code-server/Machine": open /dy-volumes/home/smu/work/workspace/.config/code-server/Machine: permission denied
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Checks:               305 / 348, 88%
Checks:               305 / 348, 88%
Elapsed time:         0.6s
Elapsed time:         0.6s
Checking:
Checking:
2023-10-06 13:06:34 ERROR : .config/code-server/extensions: failed to open directory ".config/code-server/extensions": open /dy-volumes/home/smu/work/workspace/.config/code-server/extensions: permission denied
2023-10-06 13:06:34 ERROR : .config/code-server/extensions: failed to open directory ".config/code-server/extensions": open /dy-volumes/home/smu/work/workspace/.config/code-server/extensions: permission denied
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 1 (no need to retry)
Errors:                 1 (no need to retry)
Checks:               305 / 348, 88%
Checks:               305 / 348, 88%
Elapsed time:         0.6s
Elapsed time:         0.6s
Checking:
Checking:
2023-10-06 13:06:34 ERROR : .config/code-server/User/History: failed to open directory ".config/code-server/User/History": open /dy-volumes/home/smu/work/workspace/.config/code-server/User/History: permission denied
2023-10-06 13:06:34 ERROR : .config/code-server/User/History: failed to open directory ".config/code-server/User/History": open /dy-volumes/home/smu/work/workspace/.config/code-server/User/History: permission denied
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 2 (no need to retry)
Errors:                 2 (no need to retry)
Checks:               318 / 399, 80%
Checks:               318 / 399, 80%
Elapsed time:         0.6s
Elapsed time:         0.6s
Checking:
Checking:

2023-10-06 13:06:34 ERROR : .config/code-server/User/globalStorage: failed to open directory ".config/code-server/User/globalStorage": open /dy-volumes/home/smu/work/workspace/.config/code-server/User/globalStorage: permission denied
2023-10-06 13:06:34 ERROR : .config/code-server/User/globalStorage: failed to open directory ".config/code-server/User/globalStorage": open /dy-volumes/home/smu/work/workspace/.config/code-server/User/globalStorage: permission denied
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 3 (no need to retry)
Errors:                 3 (no need to retry)
Checks:               318 / 399, 80%
Checks:               318 / 399, 80%
Elapsed time:         0.6s
Elapsed time:         0.6s
Checking:
Checking:
2023-10-06 13:06:34 ERROR : S3 bucket production-simcore path 0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace: not deleting files as there were IO errors
2023-10-06 13:06:34 ERROR : S3 bucket production-simcore path 0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace: not deleting files as there were IO errors
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 4 (no need to retry)
Errors:                 4 (no need to retry)
Checks:               444 / 444, 100%
Checks:               444 / 444, 100%
Elapsed time:         0.8s
Elapsed time:         0.8s
2023-10-06 13:06:34 ERROR : S3 bucket production-simcore path 0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace: not deleting directories as there were IO errors
2023-10-06 13:06:34 ERROR : S3 bucket production-simcore path 0318a97e-61e8-11ee-9f5c-02420a0bfeea/d09c783c-c321-5339-8f30-fc2b02b0a68e/workspace: not deleting directories as there were IO errors
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 4 (no need to retry)
Errors:                 4 (no need to retry)
Checks:               444 / 444, 100%
Checks:               444 / 444, 100%
Elapsed time:         0.8s
Elapsed time:         0.8s
2023-10-06 13:06:34 ERROR : Attempt 3/3 failed with 5 errors and: not deleting files as there were IO errors
2023-10-06 13:06:34 ERROR : Attempt 3/3 failed with 5 errors and: not deleting files as there were IO errors
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 5 (retrying may help)
Errors:                 5 (retrying may help)
Checks:               444 / 444, 100%
Checks:               444 / 444, 100%
Elapsed time:         0.8sTransferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Elapsed time:         0.8sTransferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 5 (retrying may help)
Errors:                 5 (retrying may help)
Checks:               444 / 444, 100%
Checks:               444 / 444, 100%
Elapsed time:         0.8s
Elapsed time:         0.8s
2023/10/06 13:06:34 NOTICE: 
2023/10/06 13:06:34 NOTICE: 
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Transferred:   	          0 B / 0 B, -, 0 B/s, ETA -
Errors:                 5 (retrying may help)
Errors:                 5 (retrying may help)
Checks:               444 / 444, 100%
Checks:               444 / 444, 100%
Elapsed time:         0.8s
Elapsed time:         0.8s


2023/10/06 13:06:34 Failed to sync with 5 errors: last error was: not deleting files as there were IO errors
2023/10/06 13:06:34 Failed to sync with 5 errors: last error was: not deleting files as there were IO errors
 log_level=WARNING | log_timestamp=2023-10-06 13:06:34,525 | log_source=servicelib.utils:logged_gather(127) | log_uid=None | log_msg=Error in 1-th concurrent task <coroutine object task_save_state.<locals>._save_state_folder at 0x7f05e440db60>: Error while transferring to/from S3 storage
log_level=WARNING | log_timestamp=2023-10-06 13:08:21,157 | log_source=servicelib.long_running_tasks._task:get_task_result_old(259) | log_uid=None | log_msg=Task simcore_service_dynamic_sidecar.modules.long_running_tasks.task_save_state.143dc0ec-46d1-4fa5-9a06-e1a5e52ba206 finished with error: Task simcore_service_dynamic_sidecar.modules.long_running_tasks.task_save_state.143dc0ec-46d1-4fa5-9a06-e1a5e52ba206 finished with exception: 'Error while transferring to/from S3 storage'
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/long_running_tasks/_task.py", line 418, in _progress_task
    return await handler(progress, **task_kwargs)

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_dynamic_sidecar/modules/long_running_tasks.py", line 392, in task_save_state
    await logged_gather(

  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/utils.py", line 139, in logged_gather
    raise error

  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/utils.py", line 116, in sem_task
    return await task

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_dynamic_sidecar/modules/long_running_tasks.py", line 371, in _save_state_folder
    await data_manager.push(

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_data/data_manager.py", line 183, in push
    await _push_directory(

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_data/data_manager.py", line 47, in _push_directory
    await filemanager.upload_path(

  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_sdk/node_ports_common/filemanager.py", line 332, in upload_path
    raise exceptions.S3TransferError from exc
```

### Expected Behavior

I would not expect for the service to change the permissions.

**Comment by mguidon** [comment]
In 3.0.20 I added persistency for the vscode settings. If the folder is not there, I copy over a template. Unfortunately, I am doing this while still root in the `run.bash`. Moving the code to later should fix the issue.

FYI: 3.0.18 is the exact same jupyter-smash, just without these settings.

**Comment by elisabettai** [comment]
HI @mguidon, I guess you've solved this in the latest version of smash? I've tried to open the new jupyter-smash on sim4life.io and open the VSCode extension and I don't see anymore that `.config` folder (who was owned by root and causing issues).

**Comment by mguidon** [comment]
Well, I disabled the feature in the new 8-0-0 version.

**Comment by elisabettai** [comment]
I'm closing this then, I've opened a reminder issue in the smash repo in case we need to re-enable the feature
