### ISSUE TITLE
List file metadata DB query too slow

### ISSUE THREAD

**Issue by GitHK** [ITISFoundation/osparc-simcore#4971]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which deploy/s?

production aws (e.g. osparc.io), staging aws (e.g. staging.osparc.io), production on-premise (dalco), stating on-premise (dalco), development (master), other (e.g. local)

### Current Behavior

Analysing the log below we can deduce that `storage` performance is very slow while listing files. We need to analyse the query below and figure out what makes it go so slow.

logs from storage
```
"2023-11-02T09:15:20.975Z","simcore","log_level=ERROR | log_timestamp=2023-11-02 09:15:20,973 | log_source=servicelib.aiohttp.monitoring:middleware_handler(227) | log_uid=None | log_msg=Unexpected server error ""<class 'aiohttp.web_exceptions.HTTPGatewayTimeout'>"" from access: 10.11.0.45 ""GET /v0/locations/0/files/metadata"" done in 60.23 secs. Responding with status 504
Traceback (most recent call last):
  File ""/usr/local/lib/python3.10/asyncio/tasks.py"", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ""/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/rest_middlewares.py"", line 76, in _middleware_handler
    return await handler(request)
  File ""/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/rest_middlewares.py"", line 166, in _middleware_handler
    resp = await handler(request)
  File ""/home/scu/.venv/lib/python3.10/site-packages/simcore_service_storage/utils_handlers.py"", line 29, in dsm_exception_handler
    return await handler(request)
  File ""/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/long_running_tasks/_error_handlers.py"", line 14, in base_long_running_error_handler
    return await handler(request)
  File ""/home/scu/.venv/lib/python3.10/site-packages/simcore_service_storage/handlers_files.py"", line 65, in get_files_metadata
    data: list[FileMetaData] = await dsm.list_files(
  File ""/home/scu/.venv/lib/python3.10/site-packages/simcore_service_storage/simcore_s3_dsm.py"", line 149, in list_files
    ] = await db_file_meta_data.list_filter_with_partial_file_id(
  File ""/home/scu/.venv/lib/python3.10/site-packages/simcore_service_storage/db_file_meta_data.py"", line 104, in list_filter_with_partial_file_id
    return [FileMetaDataAtDB.from_orm(row) async for row in await conn.execute(stmt)]
  File ""/home/scu/.venv/lib/python3.10/site-packages/aiopg/sa/connection.py"", line 168, in _execute
    await cursor.execute(str(compiled), post_processed_params[0])
  File ""/home/scu/.venv/lib/python3.10/site-packages/aiopg/connection.py"", line 426, in execute
    await self._conn._poll(waiter, timeout)
  File ""/home/scu/.venv/lib/python3.10/site-packages/aiopg/connection.py"", line 884, in _poll
    raise exc
  File ""/home/scu/.venv/lib/python3.10/site-packages/aiopg/connection.py"", line 881, in _poll
    await asyncio.wait_for(self._waiter, timeout)
  File ""/usr/local/lib/python3.10/asyncio/tasks.py"", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ""/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/monitoring.py"", line 183, in middleware_handler
    resp = await handler(request)
  File ""/home/scu/.venv/lib/python3.10/site-packages/aiozipkin/aiohttp_helpers.py"", line 157, in aiozipkin_middleware
    resp = await handler(request)
  File ""/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/rest_middlewares.py"", line 132, in _middleware_handler
    raise error_response from err
aiohttp.web_exceptions.HTTPGatewayTimeout
Stack (most recent call last):
  File ""/home/scu/.venv/bin/simcore-service-storage"", line 8, in <module>
    sys.exit(main())
  File ""/home/scu/.venv/lib/python3.10/site-packages/typer/main.py"", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File ""/home/scu/.venv/lib/python3.10/site-packages/click/core.py"", line 1157, in __call__
    return self.main(*args, **kwargs)
  File ""/home/scu/.venv/lib/python3.10/site-packages/typer/core.py"", line 778, in main
    return _main(
  File ""/home/scu/.venv/lib/python3.10/site-packages/typer/core.py"", line 216, in _main
    rv = self.invoke(ctx)
  File ""/home/scu/.venv/lib/python3.10/site-packages/click/core.py"", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File ""/home/scu/.venv/lib/python3.10/site-packages/click/core.py"", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ""/home/scu/.venv/lib/python3.10/site-packages/click/core.py"", line 783, in invoke
    return __callback(*args, **kwargs)
  File ""/home/scu/.venv/lib/python3.10/site-packages/typer/main.py"", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File ""/home/scu/.venv/lib/python3.10/site-packages/simcore_service_storage/cli.py"", line 40, in run
    application.run(settings_obj)
  File ""/home/scu/.venv/lib/python3.10/site-packages/simcore_service_storage/application.py"", line 99, in run
    web.run_app(
  File ""/home/scu/.venv/lib/python3.10/site-packages/aiohttp/web.py"", line 516, in run_app
    loop.run_until_complete(main_task)
  File ""/usr/local/lib/python3.10/asyncio/base_events.py"", line 636, in run_until_complete
    self.run_forever()
  File ""/usr/local/lib/python3.10/asyncio/base_events.py"", line 603, in run_forever
    self._run_once()
  File ""/usr/local/lib/python3.10/asyncio/base_events.py"", line 1909, in _run_once
    handle._run()
  File ""/usr/local/lib/python3.10/asyncio/events.py"", line 80, in _run
    self._context.run(self._callback, *self._args)
  File ""/home/scu/.venv/lib/python3.10/site-packages/aiohttp/web_protocol.py"", line 433, in _handle_request
    resp = await request_handler(request)
  File ""/home/scu/.venv/lib/python3.10/site-packages/aiohttp/web_app.py"", line 504, in _handle
    resp = await handler(request)
  File ""/home/scu/.venv/lib/python3.10/site-packages/aiohttp/web_middlewares.py"", line 117, in impl
    return await handler(request)
  File ""/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/monitoring.py"", line 227, in middleware_handler
    log.error(",,
```

logs from webserver
```
log_level=ERROR | log_timestamp=2023-11-02 10:16:42,222 | log_source=servicelib.aiohttp.monitoring:middleware_handler(227) | log_uid=None | log_msg=Unexpected server error "<class 'aiohttp.web_exceptions.HTTPGatewayTimeout'>" from access: 10.0.8.162 "GET /v0/tasks/POST%20%2Fv0%2Fprojects%3Ffrom_study%3D9ba238b2-0420-11ed-8141-02420a0b00e7.5b84a5cc-5abd-44ac-8ceb-26ace7332c73/result" done in 0.00 secs. Responding with status 504
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/rest_middlewares.py", line 76, in _middleware_handler
    return await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/rest_middlewares.py", line 166, in _middleware_handler
    resp = await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/products/_middlewares.py", line 70, in discover_product_middleware
    return await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/long_running_tasks/_error_handlers.py", line 14, in base_long_running_error_handler
    return await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/login/decorators.py", line 45, in _wrapper
    return await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/long_running_tasks.py", line 33, in _test_task_context_decorator
    return await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/long_running_tasks/_routes.py", line 67, in get_task_result
    task_result = tasks_manager.get_task_result(
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/long_running_tasks/_task.py", line 230, in get_task_result
    return tracked_task.task.result()
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/long_running_tasks/_task.py", line 418, in _progress_task
    return await handler(progress, **task_kwargs)
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/projects/_crud_api_create.py", line 239, in create_project
    ) = await _prepare_project_copy(
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/projects/_crud_api_create.py", line 73, in _prepare_project_copy
    project_data_size = await get_project_total_size_simcore_s3(
  File "/home/scu/.venv/lib/python3.10/site-packages/simcore_service_webserver/storage/api.py", line 89, in get_project_total_size_simcore_s3
    async with session.get(f"{files_metadata_url}") as response:
  File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/monitoring.py", line 183, in middleware_handler
    resp = await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/aiozipkin/aiohttp_helpers.py", line 157, in aiozipkin_middleware
    resp = await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp_session/__init__.py", line 215, in factory
    raise cast(web.HTTPException, response)
  File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp_session/__init__.py", line 199, in factory
    response = await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/rest_middlewares.py", line 132, in _middleware_handler
    raise error_response from err
aiohttp.web_exceptions.HTTPGatewayTimeout
Stack (most recent call last):
  File "/home/scu/.venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/scu/.venv/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/scu/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/home/scu/.venv/lib/python3.10/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/scu/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/home/scu/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 551, in manage_workers
    self.spawn_workers()
  File "/home/scu/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 622, in spawn_workers
    self.spawn_worker()
  File "/home/scu/.venv/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp/worker.py", line 51, in init_process
    super().init_process()
  File "/home/scu/.venv/lib/python3.10/site-packages/gunicorn/workers/base.py", line 142, in init_process
    self.run()
  File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp/worker.py", line 57, in run
    self.loop.run_until_complete(self._task)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/monitor_slow_callbacks.py", line 31, in instrumented
    retval = _run(self)
  File "/home/scu/.venv/lib/python3.10/site-packages/aiodebug/log_slow_callbacks.py", line 27, in instrumented
    return_value = _run(self)
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/scu/.venv/lib/python3.10/site-packages/servicelib/aiohttp/monitoring.py", line 227, in middleware_handler
    log.error(
```

### Expected Behavior

This should run way faster!

**Comment by bisgaard-itis** [comment]
@GitHK when the api-server is in develop mode (triggered by a env var) there is a [middleware](https://github.com/ITISFoundation/osparc-simcore/tree/master/services/api-server#profiling-requests-to-the-api-server) in place which can be used to profile the api server. I could factor this out and add it to storage as well. That wouldn't fix the issue, but then we would have a proper way of figuring out exactly which call is causing the overhead. Let me know what you think of this idea. It should be very easy to add this middleware to storage.

**Comment by GitHK** [comment]
@bisgaard-itis note that storage is an aiohttp based service (not sure how simple it is to do).

I think that if we put storage on DEBUG mode, it will print the incoming requests (access logs should be visible)

**Comment by bisgaard-itis** [comment]
> @bisgaard-itis note that storage is an aiohttp based service (not sure how simple it is to do).
> 
> I think that if we put storage on DEBUG mode, it will print the incoming requests (access logs should be visible). That way we can for sure track this.

Looks like it should be doable: https://us-pycon-2019-tutorial.readthedocs.io/aiohttp_middlewares.html
I didn't try before, but I guess that should not be too much effort

**Comment by bisgaard-itis** [comment]
> Also I am not sure if the issue with this query taking more than 20 seconds is due to:
> 
>     * running out of connections
> 
>     * db is busy
> 
>     * query is not optimised
>       The best thing to do would be to run exactly the same query against Postgres in raw SQL and see how long it takes

But if we are sure the timeout happens in a request to the DB, then I guess what we need is some debug log from that, no? Is that available?

**Comment by sanderegg** [comment]
@bisgaard-itis @GitHK to be honnest I doubt very much the DB is the one causing the timeouts.
Possible issues with the DB:
- no more clients available, but in this case it would never recover (is this the case?) that means that after a ```db_engine.acquire()``` this never returns or timesout. In this case that means  storage is limited by the amount of clients, and that would  mean a design flaw
- not possible to connect <-> network issue
- the DB itself has no more available clients <-> can be checked directly in adminer if that is the case. That would also be very bad. --> probably a design flaw in storage that creates too many clients, or recursively?
- if storage creates client recursively that can deadlock

**Comment by bisgaard-itis** [comment]
> @bisgaard-itis @GitHK to be honnest I doubt very much the DB is the one causing the timeouts. Possible issues with the DB:
> 
>     * no more clients available, but in this case it would never recover (is this the case?) that means that after a `db_engine.acquire()` this never returns or timesout. In this case that means  storage is limited by the amount of clients, and that would  mean a design flaw
> 
>     * not possible to connect <-> network issue
> 
>     * the DB itself has no more available clients <-> can be checked directly in adminer if that is the case. That would also be very bad. --> probably a design flaw in storage that creates too many clients, or recursively?
> 
>     * if storage creates client recursively that can deadlock

But wouldn't it make sense to setup some profiling tool in storage then? Then we could send a sequence of requests and investigate how the execution time changes.

**Comment by sanderegg** [comment]
@bisgaard-itis generally speaking we do not have means of profiliing the code in place. if you have an idea how to do this in a generic way (with some make recipe), that would be fore sure very helpful and not only for storage.

**Comment by bisgaard-itis** [comment]
> @bisgaard-itis generally speaking we do not have means of profiliing the code in place. if you have an idea how to do this in a generic way (with some make recipe), that would be fore sure very helpful and not only for storage.

I added middleware to the API server which does this: https://github.com/ITISFoundation/osparc-simcore/issues/4971#issuecomment-1790650658
It should be very quick to factor out and install in storage. the only issue would be that storage is aiohttp, but I think it should not be too much hazzle to adapt. With that in place one can directly profile requests to the service. Let me know if you think it is I should try to install this in storage

**Comment by sanderegg** [comment]
@bisgaard-itis I'm all for it provided you show me how this work. looks appealing. the middlewares in aiohttp are fairly easy as well, we have a bunch of them already (in webserver and storage)

**Comment by bisgaard-itis** [comment]
> @bisgaard-itis I'm all for it provided you show me how this work. looks appealing. the middlewares in aiohttp are fairly easy as well, we have a bunch of them already (in webserver and storage)

Cool, I will try to set this up for storage then. In the case of the api server it works as explained [here](https://github.com/ITISFoundation/osparc-simcore/tree/master/services/api-server#profiling-requests-to-the-api-server). One simply adds a header to the request and then gets the profile back.

**Comment by GitHK** [comment]
@sanderegg @bisgaard-itis if you search for this in graylog `""get_project_total_size_simcore_s3""` in the last 2 hours, in any deployment you will see the issue pops up multiple times.

So I'd say it's important we figure it out.

**Comment by bisgaard-itis** [comment]
@GitHK sorry for not managing to review your PR above on time. Is that one expected to solve the issue here completely?

**Comment by GitHK** [comment]
In theory It should, we need to monitor if it fixed it. Fortunately the e2e in staging will showcase the issue if still present.

**Comment by bisgaard-itis** [comment]
> In theory It should, we need to monitor if it fixed it. Fortunately the e2e in staging will showcase the issue if still present.

OK, sounds good. Thanks for the clarification

**Comment by bisgaard-itis** [comment]
@GitHK I believe the changes I have done for the metamodelling resolves this issue. As a result I close it. Please have a look at https://github.com/ITISFoundation/osparc-simcore/issues/5783 and reopen if you disagree. There is still one thing missing which is to paginate those endpoints, but the overhead is gone.
