### ISSUE TITLE
Api server should propagate 403 from catalog down to user instead of converting it into a 503

### ISSUE THREAD

**Issue by bisgaard-itis** [ITISFoundation/osparc-simcore#6782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Planned changes

When running client e2e tests I encountered

```
{
  "log_timestamp": "2024-11-21 06:36:52,154",
  "gl2_receive_timestamp": "2024-11-21 06:36:52.155",
  "HOUR": "06",
  "gl2_remote_ip": "172.16.0.11",
  "gl2_remote_port": 33611,
  "source": "simcore2",
  "gl2_source_input": "6564655cd01fb903b9554f1b",
  "image_name": "itisfoundation/api-server:v1.78.2@sha256:bbabd4309c115a7ea53efc46e12af369814eff1ab12ac01a77cd4169fd85d020",
  "gl2_processing_timestamp": "2024-11-21 06:36:52.156",
  "YEAR": "2024",
  "log_service": "production-simcore_production_api-server",
  "gl2_source_node": "ea540dfe-1c70-45a7-9879-d823bb8e4a03",
  "MINUTE": "36",
  "tag": "47ca83c7d2d7",
  "gl2_processing_duration_ms": 1,
  "timestamp": "2024-11-21T06:36:52.155Z",
  "gl2_accounted_message_size": 3243,
  "MONTHNUM": "11",
  "level": 3,
  "log_msg": "Converted status code 403 from Catalog service to status code 502\nTraceback (most recent call last):\n  File \"/home/scu/.venv/lib/python3.11/site-packages/simcore_service_api_server/exceptions/service_errors_utils.py\", line 109, in service_exception_handler\n    yield\n  File \"/home/scu/.venv/lib/python3.11/site-packages/simcore_service_api_server/exceptions/service_errors_utils.py\", line 143, in _wrapper\n    return await member_func(self, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/scu/.venv/lib/python3.11/site-packages/simcore_service_api_server/services/catalog.py\", line 138, in get_service\n    response.raise_for_status()\n  File \"/home/scu/.venv/lib/python3.11/site-packages/httpx/_models.py\", line 761, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '403 Forbidden' for url 'http://production_catalog:8000/v0/services/simcore%2Fservices%2Fcomp%2Fitis%2Fsleeper/2.1.6?user_id=238643'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403",
  "created": "2024-11-14T07:26:08.085342501Z",
  "streams": [
    "000000000000000000000001"
  ],
  "log_level": "ERROR",
  "gl2_message_id": "01JD6Q061V04AYTSPZ0WP37Z4A",
  "message": "log_level=ERROR | log_timestamp=2024-11-21 06:36:52,154 | log_source=simcore_service_api_server.exceptions.service_errors_utils:_get_http_exception_kwargs(83) | log_uid=None | log_msg=Converted status code 403 from Catalog service to status code 502\nTraceback (most recent call last):\n  File \"/home/scu/.venv/lib/python3.11/site-packages/simcore_service_api_server/exceptions/service_errors_utils.py\", line 109, in service_exception_handler\n    yield\n  File \"/home/scu/.venv/lib/python3.11/site-packages/simcore_service_api_server/exceptions/service_errors_utils.py\", line 143, in _wrapper\n    return await member_func(self, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/scu/.venv/lib/python3.11/site-packages/simcore_service_api_server/services/catalog.py\", line 138, in get_service\n    response.raise_for_status()\n  File \"/home/scu/.venv/lib/python3.11/site-packages/httpx/_models.py\", line 761, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '403 Forbidden' for url 'http://production_catalog:8000/v0/services/simcore%2Fservices%2Fcomp%2Fitis%2Fsleeper/2.1.6?user_id=238643'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403",
  "command": "/bin/sh services/api-server/docker/entrypoint.sh /bin/sh services/api-server/docker/boot.sh",
  "container_name": "production-simcore_production_api-server.1.tnyzj2ydo0z6lq2r6a7n1m9zi",
  "log_uid": "None",
  "log_source": "simcore_service_api_server.exceptions.service_errors_utils:_get_http_exception_kwargs(83)",
  "SECOND": "52,154",
  "_id": "fe33c0b1-a7d2-11ef-84c5-0242c0a80108",
  "image_id": "sha256:493d3624c5055fa38217fab5a60f9380e817a3e1af2ef489b0bec18a2131b928",
  "container_id": "47ca83c7d2d77798a22214373fe3d90368648c44b6cf73d18e65f0573f84119e",
  "MONTHDAY": "21"
}
```
Here I should have received a 403 to let me know that it is because I don't have access to that resource.

**Comment by bisgaard-itis** [comment]
Here's an additional instance where the api-server incorrectly converts a 500 to a 502:
```
Converted status code 500 from Webserver service to status code 502
Traceback (most recent call last):
  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_service_api_server/exceptions/service_errors_utils.py", line 109, in service_exception_handler
    yield
  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_service_api_server/exceptions/service_errors_utils.py", line 143, in _wrapper
    return await member_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_service_api_server/services/webserver.py", line 314, in clone_project
    result = await self._wait_for_long_running_task_results(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scu/.venv/lib/python3.11/site-packages/simcore_service_api_server/services/webserver.py", line 239, in _wait_for_long_running_task_results
    result_response.raise_for_status()
  File "/home/scu/.venv/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 We apologize for the inconvenience. Our team has recorded the issue [OEC:139698247167488] and is working to resolve it as quickly as possible. Thank you for your patience' for url 'http://10.0.8.55:8080/v0/tasks/POST%2520%252Fv0%252Fprojects%253Ffrom_study%253D7ba3716e-a8da-11ef-8e25-02420a00087f%2526hidden%253Dtrue.d2d31da1-efdf-4ae8-913e-d4493445d713/result'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
```
